Remove byteorder-dependency
actix/actix-web pull request #1023
Opened 2019-08-06 16:36 UTC by lukaslueg

This removes the `byteorder`-dependency from the `web`-component, replacing it with the `stdlib`-implementations that were stabilized in 1.32 and 1.34. Dropping a dependency is worth the change IMHO.

Notice that the calls to `.unwrap()` do not change previous behavior regarding panics.

2019-08-06 17:23 UTC, leizzer reviewed
LGTM
I don't see any issue with it. Would like to hear more from others before approving.

2019-08-06 17:30 UTC, dewey4iv commented
I took a peek; but would like the opportunity to take a closer look this evening.

2019-08-06 18:03 UTC, fafhrd91 commented on actix-http/src/ws/frame.rs
> +                let mut payload = Into::<u16>::into(reason.code).to_be_bytes().to_vec();
this is heap allocation. is it possible to avoid vec creation?

2019-08-06 18:06 UTC, fafhrd91 approved these changes

2019-08-06 20:35 UTC, dewey4iv commented
LGTM

Feels good removing dependencies.

2019-08-06 20:39 UTC, dewey4iv commented
I feel good merging this. @fafhrd91 - any objections?

2019-08-06 21:04 UTC, fafhrd91 approved these changes

2019-08-06 21:05 UTC, fafhrd91 commented
No objections, just need changes.md entry

2019-08-06 21:38 UTC, leizzer commented
@lukaslueg can you update https://github.com/actix/actix-web/blob/master/CHANGES.md under 1.0.6?

2019-08-06 21:39 UTC, leizzer requested changes
Update Changes.md

2019-08-07 14:44 UTC, lukaslueg commented
Updated. I misspoke earlier, dropping `byteorder` only affects `actix-http`, so I changed it's own `CHANGES.md`

2019-08-07 15:00 UTC, leizzer approved these changes

2019-08-07 15:00 UTC, fafhrd91 approved these changes

2019-08-07 15:28 UTC, merged