Convert Query examples to 2018 edition
actix/actix-web pull request #1120
Opened 2019-10-06 10:03 UTC by plaes

This is a RFC pull request to convert at least `types::query` examples to Rust 2018 edition.

If this is accepted, I will look into converting other examples too.

2019-10-06 11:55 UTC, fafhrd91 requested changes

2019-10-06 11:55 UTC, fafhrd91 commented on src/types/query.rs
> +/// use serde_derive::{Deserialize};
remove curly brackets

2019-10-06 11:55 UTC, fafhrd91 commented on src/types/query.rs
> +/// use serde_derive::{Deserialize};
same

2019-10-06 16:28 UTC, fafhrd91 approved these changes

2019-10-06 16:29 UTC, fafhrd91 commented
Do you want to include other changes to this PR?

2019-10-06 16:43 UTC, plaes commented
> Do you want to include other changes to this PR?

Yes, I can do the whole `src` directory.

2019-10-06 18:36 UTC, plaes commented
Most of the examples (that I knew about) should be now converted to Rust 2018 edition.

2019-10-07 03:03 UTC, JohnTitor approved these changes

2019-10-07 03:50 UTC, fafhrd91 approved these changes

2019-10-07 05:29 UTC, merged

2019-10-07 05:29 UTC, fafhrd91 commented
Thanks!