add method to match a path to a route
actix/actix-web pull request #1577
Opened 2020-06-22 14:11 UTC by Takashiidobe

This PR adds a method to match a path to a route.
This PR is for issue #1568.

I've given it a shot @robjtede, looking for your feedback, guidance, and corrections.

2020-06-23 00:08 UTC, robjtede requested changes
Rebase on master and place near the previously added match_pattern functions.
A doc test would be good on HttpRequest addition.
Extended inline documentation needed on resource map addition.
Changelog entry needed.

Thanks for picking this up :)

2020-06-23 00:08 UTC, robjtede commented on src/rmap.rs
> +        self.named.get(path)
Implementation looks good, nice handy hashmap there.

2020-06-23 00:08 UTC, robjtede commented on src/rmap.rs
> +    pub fn match_path_to_route(&self, path: &str) -> Option<&ResourceDef> {
I think `match_name` is concise and descriptive.

2020-06-23 00:08 UTC, robjtede commented on src/request.rs
> +        self.resource_map().match_path_to_route(&self.path())
Can access `self.0.rmap` directly.

2020-06-23 00:08 UTC, robjtede commented on src/request.rs
> +    pub fn match_path_to_route(&self) -> Option<&ResourceDef> {
Same as resource map, `match_name`.

2020-06-23 00:08 UTC, robjtede commented on src/request.rs
> +    fn test_match_path_to_route() {
Include a test that match names from nested resource maps. See the match_pattern PR for example of how to set this up.

2020-06-23 17:40 UTC, robjtede commented on CHANGES.md
> +* `HttpRequest::match_name` for matching a path to a route.
specify "named route"

2020-06-23 17:43 UTC, robjtede commented
Do you have a specific reason for wanting to return the entire ResourceDef? Issue #1568 only talks about returning the name.

2020-06-23 23:19 UTC, robjtede commented on src/request.rs
> +        let route_name = req.0.rmap.match_name("index");
I think this should be `match_name("/index.html")` ?
_Since the method is path in, Option(name) out?_

2020-06-23 23:23 UTC, robjtede commented on src/request.rs
> +                            );
Again here, we need to set .name("x") on the resource and assert that req.match_name().unwrap() equals "x", right?

2020-06-24 01:29 UTC, Takashiidobe commented
Thanks for your patience; I wasn't able to get the last test block (test_path_routes) to work, but match_name should now take a path and return the resource name.

2020-06-24 01:49 UTC, robjtede commented
@Takashiidobe Great work. I'll have a tinker with that other test case tomorrow then we should be able to get this merged.

2020-06-25 05:42 UTC, robjtede commented
I think we should strive that this test should pass: (Note the nested "user_post" resource)

```rust
    #[test]
    fn extract_matched_name() {
        let mut root = ResourceMap::new(ResourceDef::root_prefix(""));

        let mut rdef = ResourceDef::new("/info");
        *rdef.name_mut() = "root_info".to_owned();
        root.add(&mut rdef, None);
        println!("{:?}", &rdef);

        let mut user_map = ResourceMap::new(ResourceDef::root_prefix(""));
        let mut rdef = ResourceDef::new("/");
        user_map.add(&mut rdef, None);
        println!("{:?}", &rdef);

        let mut rdef = ResourceDef::new("/post/{post_id}");
        *rdef.name_mut() = "user_post".to_owned();
        user_map.add(&mut rdef, None);
        println!("{:?}", &rdef);

        root.add(
            &mut ResourceDef::root_prefix("/user/{id}"),
            Some(Rc::new(user_map)),
        );

        let root = Rc::new(root);
        root.finish(Rc::clone(&root));

        // sanity check resource map setup

        assert!(root.has_resource("/info"));
        assert!(!root.has_resource("/bar"));

        assert!(root.has_resource("/user/22"));
        assert!(root.has_resource("/user/22/"));
        assert!(root.has_resource("/user/22/post/55"));

        println!("{:?}", &root);

        // extract patterns from paths

        assert!(root.match_name("/bar").is_none());
        assert!(root.match_name("/v44").is_none());
        assert_eq!(root.match_name("/user/22"), None);
        assert_eq!(root.match_name("/user/22/"), None);
        assert_eq!(root.match_name("/info"), Some("root_info"));
        assert_eq!(root.match_name("/user/22/post/55"), Some("user_post"));
    }
```

To do that, there will need to be some recursive search in match_name. Check out has_resource and match_pattern.

Other considerations:
- we can return `Option<&str>` and save an allocation
- Empty names should return None

2020-06-26 00:08 UTC, Takashiidobe commented
I gave it a shot, but I can't figure out how to recurse through the route and return the name of the route, unfortunately.  I can give the issue up to someone else or let you take it over the finish line.

2020-06-26 00:32 UTC, robjtede commented
Okay. Thanks for your effort!

2020-06-26 19:12 UTC, robjtede approved these changes

2020-06-27 10:50 UTC, JohnTitor approved these changes
Awesome!

2020-06-27 15:22 UTC, merged

2020-06-30 13:38 UTC, Takashiidobe commented
Thanks for your work on this issue Rob, your help was much appreciated.