Configurable trailing slash behaviour for NormalizePath
actix/actix-web pull request #1639
Opened 2020-08-18 06:14 UTC by ljoonal

## PR Type

Feature

## PR Checklist
Check your PR fulfills the following:

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [ ] A changelog entry has been made for the appropriate packages.
- [ ] Format code with the latest stable rustfmt

## Overview

Currently NormalizePath always adds a trailing slash. This change would make it configurable to either follow that style, or to always trim the trailing slash instead.

Will be a breaking change to `NormalizePath` usage, since `middleware::NormalizePath` will need to be replaced by `middleware::NormalizePath::default()` or `::new(...)` when creating the middleware.

Closes #1612

2020-08-18 10:24 UTC, robjtede requested changes
Looks really good so far. Just left some initial thoughts and obviously the checks are failing from the doc comment in condition.rs.

2020-08-18 10:24 UTC, robjtede commented on src/middleware/normalize.rs
> +    trim_last_slash: bool,
Given how we're using it, makes sense to keep the enum here too. Makes for more expressive matches later and possible ease of extensibility.

2020-08-18 10:24 UTC, robjtede commented on src/middleware/normalize.rs
> +}
If we impl Default for TrailingSlash we can keep the derive on NormalizePath.

2020-08-18 10:24 UTC, robjtede commented on src/middleware/normalize.rs
> +    /// Always add a trailing slash to the end of the path.
Make a note that all routes defined must end in trailing slash for them to to be accessible.

2020-08-18 10:24 UTC, robjtede commented on src/middleware/normalize.rs
> +    async fn trim_trailing_slashes() {
Also include a test request without trailing slash.

2020-08-18 10:24 UTC, robjtede commented on src/middleware/normalize.rs
> +            true => original_path.trim_end_matches(|c| c == '/').to_string(),
I believe this is equivalent.

```suggestion
            true => original_path.trim_end_matches('/').to_string(),
```

2020-08-18 10:24 UTC, robjtede commented on src/middleware/normalize.rs
> +pub enum TrailingSlash {
Can you stick a #[non_exhaustive] on this please. Unlikely folks will want to match on it but would let us do things in future without breaking changes.

2020-08-18 12:39 UTC, robjtede commented
Thanks for those updates. Add a CHANGELOG.md entry and a note to MIGRATION.md. Also check the job failure to see what needs updating.

2020-08-19 11:20 UTC, robjtede approved these changes

2020-08-19 11:21 UTC, merged

2020-08-19 11:22 UTC, robjtede commented
Great work, thanks 👍

2020-08-28 17:35 UTC, patrickelectric commented
Hey, any plan to release it ?