awc: Provide Reqwest-like crate doc-comment
actix/actix-web pull request #1656
Opened 2020-09-08 17:48 UTC by popzxc

## PR Type

Docs

## PR Checklist
Check your PR fulfills the following:

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [ ] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt

## Overview

Subjectively, one great part of `reqwest` is its documentation, which provides usage examples for most common users' needs right on the main page of `docs.rs`.

This PR extends the `awc main doc-comment with the similar list of examples, so that users can see how to use library without digging deep into the crate docs (or even the source code).

2020-09-08 18:06 UTC, popzxc commented
CI fails due to error in `actix-http`:

```
error[E0432]: unresolved import `actix_tls::SslError`
##[error]   --> actix-http/src/service.rs:198:46
    |
198 |     use actix_tls::{openssl::HandshakeError, SslError};
    |                                              ^^^^^^^^ no `SslError` in the root

error[E0432]: unresolved import `actix_tls::SslError`
##[error]   --> actix-http/src/h1/service.rs:101:46
    |
101 |     use actix_tls::{openssl::HandshakeError, SslError};
    |                                              ^^^^^^^^ no `SslError` in the root

error[E0432]: unresolved import `actix_tls::SslError`
##[error]   --> actix-http/src/h2/service.rs:100:46
    |
100 |     use actix_tls::{openssl::HandshakeError, SslError};
    |                                              ^^^^^^^^ no `SslError` in the root

error: aborting due to 3 previous errors
```

Not sure if I should do something about it `¯\_(ツ)_/¯`

2020-09-08 18:08 UTC, robjtede commented
Nope CI failures are not your fault. Just need to rebase onto #1655 when it's merged.

2020-09-09 03:56 UTC, Neopallium commented on awc/src/lib.rs
> +//! `awc` is a HTTP/WebSocket library implemented atop of `actix` stack.
'is a HTTP/WebSocket Client library..."

2020-09-09 03:58 UTC, Neopallium approved these changes

2020-09-09 11:02 UTC, robjtede requested changes

2020-09-09 11:02 UTC, robjtede commented on awc/src/lib.rs
> +//! `awc` is a HTTP/WebSocket Client library implemented atop of `actix` stack.
Don't want to suggest is is using the `actix` crate.

```suggestion
//! `awc` is a HTTP and WebSocket client library built using the Actix ecosystem.
```

2020-09-09 11:02 UTC, robjtede commented on awc/src/lib.rs
> +/// An asynchronous web Client.
```suggestion
/// An asynchronous HTTP and WebSocket client.
```

2020-09-09 11:02 UTC, robjtede commented on awc/src/lib.rs
> +//! # use actix_rt::System;
None of these imports should be needed.

```suggestion
```

2020-09-09 11:02 UTC, robjtede commented on awc/src/lib.rs
> +//! map.insert("body", "json");
would prefer the use of the serde_json::json! construction.

2020-09-09 11:02 UTC, robjtede commented on awc/src/lib.rs
> +//! let response = client.get("http://www.rust-lang.org") // <- Create request builder
if this can work with minimal change as the https url then would prefer that

2020-09-09 11:11 UTC, robjtede requested changes

2020-09-09 11:11 UTC, robjtede commented on awc/src/lib.rs
> +//! let mut request = serde_json::json!({
```suggestion
//! let request = serde_json::json!({
```

2020-09-09 11:17 UTC, robjtede approved these changes
nice job, thanks 👍

2020-09-09 12:53 UTC, popzxc commented
Ah, Windows tests fail the same way as in #1654.

I'll restore URLs to HTTP and open an issue.

2020-09-09 13:23 UTC, robjtede commented
> I'll restore URLs to HTTP

Fair enough. We'll merge with this and I shall try to remember to change them back to HTTPS before stable release. We should get this working on Windows.

2020-09-09 13:24 UTC, merged