Implement regex log exclusion rules
actix/actix-web pull request #1723
Opened 2020-10-03 08:28 UTC by mattgathu

## PR Type

Feature

## PR Checklist
Check your PR fulfills the following:

- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] A changelog entry has been made for the appropriate packages.
- [ ] Format code with the latest stable rustfmt

## Overview
Support use of regex for logger exclusion rules

part of #1682

2020-10-09 12:17 UTC, robjtede commented on CHANGES.md
> +* Implement Logger middleware regex exclude pattern [#1723]
move this and link line to unreleased section

2020-10-12 00:30 UTC, robjtede requested changes
Looks alright so far. I think that middleware constructors should panic on invalid input so we can either just panic or require that a regex is passed in that we extract the known good pattern from.

2020-10-12 00:30 UTC, robjtede commented on src/middleware/logger.rs
> +            exclude_regex: RegexSet::new(Vec::<&str>::new()).unwrap(),
```suggestion
            exclude_regex: RegexSet::empty(),
```

2020-10-12 00:30 UTC, robjtede commented on src/middleware/logger.rs
> +            exclude_regex: RegexSet::new(Vec::<&str>::new()).unwrap(),
I got `RegexSet::empty` added to `regex` v1.4.

```suggestion
            exclude_regex: RegexSet::empty(),
```

2020-10-12 00:30 UTC, robjtede commented on src/middleware/logger.rs
> +            exclude_regex: RegexSet::new(Vec::<&str>::new()).unwrap(),
also will need the cargo toml regex version bumping

2020-10-12 00:30 UTC, robjtede commented on src/middleware/logger.rs
> +        let mut patterns: Vec<String> = inner.exclude_regex.patterns().into();
```suggestion
        let mut patterns = inner.exclude_regex.patterns().to_vec();
```

2020-10-18 05:42 UTC, mattgathu commented
> Looks alright so far. I think that middleware constructors should panic on invalid input so we can either just panic or require that a regex is passed in that we extract the known good pattern from.

I went with panic, to avoid the user having to rely on the regex crate and also avoid incompatibility if the user's regex crate version significantly differs from the one used by Actix.

2020-10-19 05:33 UTC, robjtede approved these changes
I agree that not forwarding (leaking) the regex error type is a compelling reason to panic instead. Thanks for tackling this.

2020-10-19 06:18 UTC, merged