Tokio 0.3
actix/actix-web pull request #1813
Opened 2020-12-05 06:00 UTC by fakeshadow

## PR Type

Update

## PR Checklist
Check your PR fulfills the following:

- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt

## Overview

Blocked by upstream deps that are not released.
progress can be tracked by https://github.com/actix/actix-net/pull/204

2020-12-11 06:40 UTC, yjhmelody commented
Maybe it is better to wait for tokio 1.0?

2020-12-11 06:59 UTC, fakeshadow commented
yea this PR is not meant to be the next elease version.

2020-12-31 08:20 UTC, therealprof commented
@fakeshadow What's the/your timeline for this? Need a hand?

2020-12-31 08:26 UTC, fakeshadow commented
> @fakeshadow What's the/your timeline for this? Need a hand?

Thanks for asking. This is mostly done with only deps get in the way.
at least `actix`, `actix-service` `actix-server` need a new release to make it pass all CI.

2021-01-03 18:16 UTC, robjtede requested changes
feels like there's some missing changelog items which are easily forgotten

2021-01-03 18:16 UTC, robjtede commented on CHANGES.md
> +* Update `rust-tls` to `0.19.0`
reference PR

worth mentioning other upgrades in here too

2021-01-03 18:16 UTC, robjtede commented on actix-files/CHANGES.md
> +* Update `bytes` to `1`.
reference PR

2021-01-03 18:16 UTC, robjtede commented on actix-files/Cargo.toml
> +futures-util = { version = "0.3.7", default-features = false, features = ["sink"] }
appears to be needless feature

2021-01-03 18:16 UTC, robjtede commented on actix-http-test/CHANGES.md
> +* Update `bytes` to `1`.
reference PR

2021-01-03 18:16 UTC, robjtede commented on actix-http/CHANGES.md
> +* Upgrade `h2` to `0.3`
reference PR

2021-01-03 18:16 UTC, robjtede commented on actix-multipart/CHANGES.md
> +* Update `bytes` to `1`
reference PR

2021-01-03 18:16 UTC, robjtede commented on actix-web-actors/CHANGES.md
> +* Update `bytes` to `1`.
reference PR

2021-01-03 18:16 UTC, robjtede commented on awc/CHANGES.md
> +* Update `rust-tls` to `0.19.0`
reference PR

2021-01-03 18:16 UTC, robjtede commented on awc/src/ws.rs
> -        #[allow(clippy::field_reassign_with_default)]
keep this to squelch warning

2021-01-03 18:16 UTC, robjtede commented on src/server.rs
>      pub fn backlog(mut self, backlog: i32) -> Self {
todo: use u32 here too

2021-01-03 23:46 UTC, robjtede approved these changes

2021-01-03 23:47 UTC, merged