Implement getters for named file fields
actix/actix-web pull request #2021
Opened 2021-02-22 10:58 UTC by SuperFluffy

## PR Type

Feature

## PR Checklist
- [ ] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [ ] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt.
- [ ] (Team) Label with affected crates and semver status.

## Overview

I wanted to change `ContentDisposition` to always be `attachment` no matter the underlying file type. But since there is currently no way to retrieve the current content disposition of `NamedFile`, I would have to guess the `filename` parameter for this header.

And since the other fields might also potentially be interesting to users, getter methods for those were added as well.

## No flag getter

I did not add `pub fn flags(&self) -> &Flags`, because having the bit mask is quite meaningless without knowing what the bits stand for. Since there is no `set_flags` setter either, should we add methods like `pub fn is_FLAG_set(&self) -> bool`? For example, `pub fn is_etag_set(&self) -> bool`?

2021-02-26 12:33 UTC, SuperFluffy commented
Are you fine with the `tests` being doc tests that just check for compilation, similar to the `path` and `file` getters?

Also, should I add some methods to check if flags are set?

2021-02-26 19:01 UTC, robjtede requested changes
otherwise, looks okay. for is_*_set, we can omit it for now unless someone brings a use case

2021-02-26 19:01 UTC, robjtede commented on actix-files/src/named.rs
> +    pub fn md(&self) -> &Metadata {
would call this `metadata`

2022-03-10 01:25 UTC, robjtede commented
superseded by #2689

2022-03-10 01:25 UTC, closed without merging