fix connection data on keep alive connections
actix/actix-web pull request #2327
Opened 2021-07-12 17:38 UTC by robjtede

## PR Type

Fix

## PR Checklist

- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] A changelog entry has been made for the appropriate packages.
- [ ] Format code with the latest stable rustfmt.
- [x] (Team) Label with affected crates and semver status.

## Overview
Fixed in a non-ideal way; looking for alternatives.

closes #1770

2021-07-15 15:43 UTC, ibraheemdev requested changes

2021-07-15 15:43 UTC, ibraheemdev commented on actix-http/src/extensions.rs
> +
```suggestion
```
I think this method should be removed and the unsafe downcast should be moved to the place it is used and it is guaranteed that `T` is the true type. Right now this method could be used unsoundly, and even though it's not exposed, I think it's better to limit the scope of the unsafety.

2021-07-15 15:43 UTC, ibraheemdev commented on actix-http/src/extensions.rs
> +            .and_then(downcast_cloneable)
```suggestion
        if let Some(old) = self.map.insert(TypeId::of::<T>(), Box::new(val)) {
            // Safety:
            // Box is owned and `T` is known to be the true type from the map containing TypeId as key.
            *unsafe { UncheckedAnyExt::downcast_unchecked::<T>(boxed) }
        }
```
Per above.

2021-12-05 22:17 UTC, robjtede commented
Could do with an opinion on whether this is a good enough fix for v4 or wether we should seriously look at an alterative solution like connection-level state.

2021-12-07 17:23 UTC, closed without merging