temp
actix/actix-web pull request #2745
Opened 2022-04-25 13:48 UTC by robjtede

## PR Type

PR_TYPE

## PR Checklist

- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] A changelog entry has been made for the appropriate packages.
- [ ] Format code with the latest stable rustfmt.
- [ ] (Team) Label with affected crates and semver status.

## Overview

2022-05-11 02:30 UTC, Geometrically requested changes
Does this PR retain

2022-05-11 02:30 UTC, Geometrically commented on actix-http/src/h1/dispatcher_tests.rs
> +            payload dropped
Does this payout retain responses a server gives when a payload is dropped? That is the intended behavior IMO, and is what actix did before 4.0.

2022-06-09 00:15 UTC, Geometrically commented
Regarding my previous comment, I don't think this is the case. We have deployed this fix in production at Modrinth, and users still are getting payload drops on their multipart requests.

This is a really big issue as when the payload drops and actix closes the connection, CORS headers aren't set so we can't access the response. This PR hasn't fixed the bug in my issue.

I feel like the previous approach was a lot better. The previous "fix" was for a very small use case. This issue is affecting big projects like MeiliSearch, and I don't think it fits with the actix architecture.

IMO, if I return an error in my response to a user, they should get that error. The connection shouldn't be instantly closed.

(Sorry if this wording was harsh- it's just a pretty big issue my team and I have been dealing with for the past couple of months)

2022-06-09 01:02 UTC, robjtede commented
I understand the severity of the issue (we're hitting this at my work as well) and also that this PR is an incomplete fix, hence why it is not merged and released.

I'm going to revert the change that created this problem, which will give us back the other bug that existing in v3 (citation needed) which was relatively less problematic. This will give me and anyone else who wants to try some more time to debug and fix both problems finally.

Expect v4.1 to be out by EOD Thursday.

2022-06-09 01:52 UTC, Geometrically commented
Thanks a lot for your work on actix :smile: 

Glad this issue is being fixed and love the work the team is doing. Besides this, actix has been an amazing platform for us to build our API on, and for that I am very thankful :heart: 

Can't wait for 4.1!

2022-07-04 17:51 UTC, Geometrically commented
Hey, I noticed this was moved to v4.2. Is there a fix for this issue being planned? Or at least a fork we can use which resolves it to the prior system?

2026-09-01 01:10 UTC, closed without merging