Update base64 to 0.21
actix/actix-web pull request #2966
Opened 2023-01-16 12:47 UTC by citreae535

## PR Type

Dependency update

## PR Checklist

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt.
- [ ] (Team) Label with affected crates and semver status.

## Overview

Update base64 to 0.21 (MSRV 1.57) and refactor deprecated API calls

2023-01-16 14:15 UTC, robjtede requested changes

2023-01-16 14:15 UTC, robjtede commented on actix-http-test/CHANGES.md
> +- Update `base64` to `0.21`.
as these are not user facing changes, no need for any changelog updates 👍🏻

2023-01-16 14:15 UTC, robjtede commented on awc/src/builder.rs
> +use base64::{prelude::BASE64_STANDARD, Engine};
if prelude is being used, then lets just use it

```suggestion
use base64::prelude::*;
```

2023-01-16 15:26 UTC, citreae535 commented
A cursory search shows that `base64` does not seem to be used by `actix-http-test`. Maybe it can be removed from that crate.

2023-01-21 00:18 UTC, robjtede approved these changes
thanks 👍🏻

2023-01-21 01:36 UTC, merged