Add FromRequest<S> implementation for Option<T> and Result<T> where T: FromRequest<S>
actix/actix-web pull request #416
Opened 2018-07-23 13:33 UTC by axos88

This pull request adds an implementation of  `FromRequest<S>` for `Option<T>` and `Result<T>` where `T: FromRequest<S>`.

In case the `FromRequest<T>` extractor fails for any reason the `FromRequest<Option<T>>` returns `None`, the `FromRequest<Result<T>>` return the Error itself. They do not fail the request, so it is available and can be handled within the handler.

They can be useful for example when extracting `Authorization` / `Cookie` / `Session` / `Header` / `X` information that may or may not be present for the request.

2018-07-23 17:18 UTC, fafhrd91 requested changes

2018-07-23 17:18 UTC, fafhrd91 commented on src/extractor.rs
> +//                    if true { panic!("{:?}", e.as_response_error()); }
remove this line

2018-07-23 17:18 UTC, fafhrd91 commented on src/extractor.rs
> +//    #[test]
uncomment or remove

2018-07-23 17:18 UTC, fafhrd91 commented on src/extractor.rs
> +use futures::future;
move this to line 9

2018-07-23 17:18 UTC, fafhrd91 commented on src/extractor.rs
> +use Result;
remove this, use `Result<T, Error>` instead

2018-07-24 07:43 UTC, axos88 commented
Rebase onto actix-web/master

2018-07-24 16:59 UTC, fafhrd91 approved these changes
could you add entry to changes.md

2018-07-24 21:06 UTC, fafhrd91 commented
very good! thanks!

2018-07-24 21:06 UTC, merged