show index if index file doesn't exist
actix/actix-web pull request #650
Opened 2018-12-29 13:44 UTC by esjeon

Currently, `show_index` is completely ignored if `index_file` is set. It's saner to show index if the designated index file doesn't exist.

2018-12-29 18:12 UTC, DoumanAsh commented
I'm not sure if it is actually saner?

If user specifies `index_file` then he expects to have file, if there is no file it might be actually error?
But I'm not sure to be honest, maybe it does make sense

2018-12-30 02:24 UTC, esjeon commented
Well, at least, [that's how Apache works](https://wiki.apache.org/httpd/DirectoryListings), and this is useful during development. With this, you can load up application normally, and then poke around files freely using directory listing.

Or perhaps, this would better be provided by 3rd-party middleware, because Apache-like behaviour would  not be a main goal of http framework. Still, it's just few lines of code. (Note: Apache does have it in a module called _mod_autoindex_)

2018-12-30 18:15 UTC, DoumanAsh requested changes

2018-12-30 18:15 UTC, DoumanAsh commented on src/fs.rs
> +                if !path.exists() {
We should show index only if `C::show_index()` returns true!

2018-12-31 06:36 UTC, DoumanAsh approved these changes

2018-12-31 06:37 UTC, DoumanAsh commented
Thank you, please add note on new change in [CHANGES.md](https://github.com/actix/actix-web/blob/master/CHANGES.md)

2019-01-03 09:36 UTC, merged

2019-01-03 09:37 UTC, DoumanAsh commented
Thanks