Log error results in Logger middleware (closes #938)
actix/actix-web pull request #984
Opened 2019-07-17 18:45 UTC by vmalloc

2019-07-17 22:47 UTC, fafhrd91 requested changes
Could you add entry to changes

2019-07-17 22:47 UTC, fafhrd91 commented on src/middleware/logger.rs
> +            debug!("Error in response: {:?}", error);
You should filter 500.

2019-07-18 07:25 UTC, vmalloc commented on src/middleware/logger.rs
> +            debug!("Error in response: {:?}", error);
done

2019-07-18 07:25 UTC, vmalloc commented
Added to changelog

2019-07-18 08:29 UTC, fafhrd91 approved these changes

2019-07-18 08:31 UTC, fafhrd91 commented
thanks!

2019-07-18 08:31 UTC, merged